### ISSUE TITLE
scrollTo hinzufügen um nach reload an den Anfang zu kommen

### ISSUE THREAD

**Issue by zonky2** [trilobit-gmbh/contao-ajaxpagination-bundle#3]
scrollTo hinzufügen um nach reload an den Anfang zu kommen - insbesondere in der Mobilansicht sind die neuen Items nicht zu sehen

**Comment by trilobit-gmbh** [comment]
Hallo @zonky2,

in der (aktuellen) jQuery-Version werden Events gefeuert die verwendet werden können dafür; hier ein kleines Snippet wie ich es in einem Projekt einsetze.

```
let paginations = jQuery('[data-pagination]');
let hash = window.location.hash;

paginations
    .on('hide.pagination.container', function () {
    })
    .on('show.pagination.container', function (event) {
        let target = jQuery(event.relatedTarget[0]);

        // hier das Scroll-Top
        // target.offset().top;
    })
;
```

**Comment by zonky2** [comment]
o.k. - ich würde aber das als "allgemeines Feature" ansehen und fix in den Code einbauen

**Comment by Lelia155** [comment]
Wo genau muss das denn hin? Stehe vor dem gleichen Problem, dass er nach dem reload an den Anfang scrollen muss.

**Comment by trilobit-gmbh** [comment]
Hallo @Lelia155 ,
das muss in ein eigenes Javascript eingebaut werden (welches Du ggf schon für andere Zwecke hast; wenn nicht; vgl: https://community.contao.org/de/showthread.php?69632-Java-Script-Code-einbinden)

Wenn Dir das so nicht weiterhilft kann ich gerne auch (dann jedoch kostenpflichtigen) Support anbieten.
Schreib mir dann einfach an peter.adelmann@trilobit.de ;-) mit ein paar Rahmeninformationen (ob Du z.B. schon ein eigenes Javascript hast, wie das eingebunden ist; einen Bspl-Link zur Seite; ...). Dann kann ich Dir ggf die Ergänzung zum bestehenden eigenen Javascript erstellen oder ein Mini-Javascript mit Hinweisen zum einbinden geben.

Viele Grüße
Peter, trilobit GmbH

**Comment by trilobit-gmbh** [comment]
See 1.2.0
