### ISSUE TITLE
Nachladen statt neuladen

### ISSUE THREAD

**Issue by landzone21** [trilobit-gmbh/contao-ajaxpagination-bundle#4]
Ist es möglich, die Datensätze einer weiteren Seite einfach nachzuladen statt neu zu laden, also die Daten der vorigen Seite stehen zu lassen? Also das typische "Zeige mehr Ergebnisse"?
Wie müsste man das JS anpassen?

**Comment by trilobit-gmbh** [comment]
Ja, das geht ;-)

vgl Doku: `<div data-pagination="..." data-pagination-type="add" data-pagination-opacity=".25">`

Due musst dann jedoch die Paginierungs-Links so modifizieren (z.B. via CSS), dass nur noch der "Weiter" Link übrig bleibt.
Dann werden die neuen Inhalte angefügt statt ausgetauscht.

Viele Grüße
Peter
